# Generated by Django 4.2.23 on 2026-08-16 01:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('edition', models.TextField(blank=True, default='')),
                ('alt_titles', models.TextField(blank=True, default='')),
                ('cover_url', models.URLField(blank=True, default='')),
            ],
            options={
                'db_table': 'catalog',
            },
        ),
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('cover_url', models.URLField(blank=True, default='')),
                ('spine_b64', models.TextField(blank=True, default='')),
                ('confidence', models.FloatField(default=0.0)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('catalog_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.catalogbook')),
            ],
            options={
                'db_table': 'library',
                'ordering': ['-confirmed_at'],
            },
        ),
    ]
